export const daysList = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const monthList = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const todos = [
  {
    title: "Complete React Assignment",
    description:
      "Finish the to-do list feature implementation for the project.",
    dueDate: "2025-01-28",
    imgSrc: "react-assignment.png",
    priority: "High",
    status: "In Progress",
    createdOn: "2025-01-24",
    steps: [
      "Create components",
      "Implement state management",
      "Test functionality",
    ],
  },
  {
    title: "Grocery Shopping",
    description: "Buy groceries for the week.",
    dueDate: "2025-01-25",
    imgSrc: "grocery-items.png",
    priority: "Medium",
    status: "Not Started",
    createdOn: "2025-01-23",
    steps: ["Make a list", "Visit the store", "Purchase items"],
  },
  {
    title: "Team Meeting",
    description: "Discuss project updates and next steps with the team.",
    dueDate: "2025-01-26",
    imgSrc: "team-meeting.png",
    priority: "High",
    status: "Scheduled",
    createdOn: "2025-01-24",
    steps: ["Prepare agenda", "Send invites", "Take meeting notes"],
  },
  {
    title: "Workout Routine",
    description: "Follow the planned workout schedule for the week.",
    dueDate: "2025-01-30",
    imgSrc: "workout-schedule.png",
    priority: "Low",
    status: "In Progress",
    createdOn: "2025-01-22",
    steps: ["Warm-up exercises", "Strength training", "Cool-down stretches"],
  },
  {
    title: "Submit Tax Documents",
    description:
      "Organize and submit required tax documents to the accountant.",
    dueDate: "2025-02-01",
    imgSrc: "tax-documents.png",
    priority: "High",
    status: "Not Started",
    createdOn: "2025-01-20",
    steps: ["Gather receipts", "Review forms", "Send documents"],
  },
  {
    title: "Plan Birthday Party",
    description: "Organize a birthday party for my son.",
    dueDate: "2025-02-15",
    imgSrc: "birthday-party.png",
    priority: "High",
    status: "Not Started",
    createdOn: "2025-01-23",
    steps: ["Book venue", "Send invitations", "Order cake"],
  },
  {
    title: "Car Maintenance",
    description: "Take the car for a scheduled service.",
    dueDate: "2025-01-29",
    imgSrc: "car-maintenance.png",
    priority: "Medium",
    status: "Scheduled",
    createdOn: "2025-01-22",
    steps: ["Check tire pressure", "Change oil", "Inspect brakes"],
  },
  {
    title: "Learn React Testing Library",
    description:
      "Study and practice testing React components using React Testing Library.",
    dueDate: "2025-02-10",
    imgSrc: "react-testing.png",
    priority: "Medium",
    status: "In Progress",
    createdOn: "2025-01-21",
    steps: [
      "Read documentation",
      "Write unit tests",
      "Implement integration tests",
    ],
  },
  {
    title: "Read a Book",
    description: "Finish reading 'Clean Code' by Robert C. Martin.",
    dueDate: "2025-03-01",
    imgSrc: "clean-code.png",
    priority: "Low",
    status: "Not Started",
    createdOn: "2025-01-20",
    steps: ["Read chapter 1", "Highlight key points", "Write a summary"],
  },
  {
    title: "Redesign Website",
    description:
      "Revamp the personal portfolio website for better user experience.",
    dueDate: "2025-03-15",
    imgSrc: "website-redesign.png",
    priority: "High",
    status: "Planning",
    createdOn: "2025-01-24",
    steps: ["Research trends", "Sketch wireframes", "Develop components"],
  },
];
